### PR TITLE
Use breaking version bump for fluent

### LINKED ISSUE #384: fluent 0.16.2 contains breaking changes
`fluent` 0.16.2 changed its `fluent-bundle` dependency from 0.15.3 to 0.16. `fluent-bundle` 0.16.0 changed its `fluent-syntax` dependency from 0.11.1 to 0.12.

`fluent` has types from `fluent-syntax` (at least `ast::Pattern` and `ast::Entry`) in its public API, so that `fluent` 0.16.1 uses types from `fluent-syntax` 0.11 while `fluent` 0.16.2 uses types from `fluent-syntax` 0.12. This is a breaking change as they are technically different types.

The issue manifests at least in `i18n-embed` (0.15.4) as it uses `fluent` 0.16 with types from `fluent-syntax` 0.11. This works fine with 0.16.1 (and I suppose 0.16.0),  but breaks with 0.16.2 which expects `fluent-syntax` 0.12 types.

Reproducer:
```sh
cargo init
cargo add i18n-embed -F fluent-system
cargo build
💥
```

### LINKED ISSUE #385: It seems `fluent_bundle` is a "public dependency"  of `fluent`. So a semver bump in `fluent_bundle` should require a semver bump in `fluent`.
> It seems `fluent_bundle` is a "public dependency"  of `fluent`. So a semver bump in `fluent_bundle` should require a semver bump in `fluent`.
>
> The result of this is that projects depending on `fluent` and `i18n-embed` are getting errors about incompatible types (from different versions of `fluent-syntax`) when running `cargo update`.

_Originally posted by @ids1024 in https://github.com/projectfluent/fluent-rs/issues/383#issuecomment-2902814140_

### PR DESCRIPTION
**Pull request by alerque**
* Closes #384
* Closes #385
* See also comments in #383.

It seems we have an issue with downstream projects using (indirectly) `fluent-bundle::*` while at the same time the upstream project is using `fluent::fluent_bundle::*`. This is kind of a weird arrangement, but given that we're exposing it it does seem like the resolver has trouble getting the right combination.

Note `cargo semver-checks` did *not* catch this, but that may be a bug.

If we yank 0.16.2 and replace it with 0.17.0 we might mitigate some of the pain downstream.

Thoughts?

### CODE REVIEW

**Comment by alerque** [comment]
I just yanked fluent-0.16.2.

**Review by zbraniecki — APPROVED** [review]
thanks for responding so fast!
